// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";
const {
  initializeApp,
  applicationDefault,
  cert,
} = require("firebase-admin/app");
const {
  getFirestore,
  Timestamp,
  FieldValue,
} = require("firebase-admin/firestore");
const serviceAccount = require("../../creds.json");

initializeApp({
  credential: cert(serviceAccount),
});

const db = getFirestore();

// This handler supports both GET and POST requests.
// GET will return all orders.
// POST will attempt to create a new order and return the resulting ID.
export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<any>
) {
  if (req.method === "GET") {
    // fetch all orders
    const snapshot = await db.collection("orders").get();
    const result: any = [];
    snapshot.forEach((doc: any) => {
      result.push(doc.data());
    });

    res.status(200).json(result);
  } else if (req.method === "POST") {
    // add new order with an autogenerated ID
    // do some validation

    const doc = await db.collection("orders").add(req.body);

    res.status(200).json(doc.id);
  } else {
    res.status(400).json("Unable to handle request");
  }
}
